[build]
  publish = "build"
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS redirects
[[redirects]]
  from = "http://facturation.almadinahboutique.com/*"
  to = "https://facturation.almadinahboutique.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.facturation.almadinahboutique.com/*"
  to = "https://facturation.almadinahboutique.com/:splat"
  status = 301
  force = true

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
